In [1]:
!pip install numpy


[notice] A new release of pip is available: 23.1.2 -> 23.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

a=np.array([1,2,3,4,5])
print("Array list \n",a)

zero_a=np.zeros((3,4))
print("Array list zeros \n",zero_a)

one_a=np.array((2,2))
print("Array list ones\n",one_a)

randonm_a=np.random.rand(2,2)
print("Array list \n",randonm_a)

Array list 
 [1 2 3 4 5]
Array list zeros 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array list ones
 [2 2]
Array list 
 [[0.7687996  0.57925409]
 [0.58460193 0.08941118]]


In [3]:
#broadcasating example
b=np.array([2,4,6])
scalar=2
result=b*scalar
print("broadcasting", result)

broadcasting [ 4  8 12]


In [4]:
#element-wise Arithmetic operations.
a=np.array([1,2,3])
b=np.array([7,8,9])
print("Addition",a+b)
print("Subtraction",a-b)
print("Division",a/b)
print("Multiplication",a*b)

#matrix operation
mat_a=np.array([[1,3],[5,7]])
mat_b=np.array([[2,4],[6,8]])
mat_prod=np.dot(mat_a,mat_b)
print("matrix Product \n",mat_prod)

# statistical functions
data = np.array([10, 15, 20, 25, 30]) 
print(data)
mean = np.mean(data)
print("Mean", mean)
median = np.median(data)
print("Median", median)
std_deviation = np.std(data)
print("std Deviation", std_deviation)

Addition [ 8 10 12]
Subtraction [-6 -6 -6]
Division [0.14285714 0.25       0.33333333]
Multiplication [ 7 16 27]
matrix Product 
 [[20 28]
 [52 76]]
[10 15 20 25 30]
Mean 20.0
Median 20.0
std Deviation 7.0710678118654755


In [5]:
arr = np.array([10, 20, 30, 40, 50])
# Accessing elements using indexing 
element = arr[0] #Access the first element (10) 
print("[0] ",element)
element0 = arr[-1] # Access the last element (50)
print("[-1] ",element0)

[0]  10
[-1]  50


In [6]:
#slicing
slice0= arr[1:4] # Get elements from index 1 to index 3 (20, 30, 40) 
print("arr[1:4] ",slice0) 
slice1 = arr[:3] #Get elements from the beginning up to index 2 (10, 20, 30)
print("arr[:3] ",slice1)
slice2= arr[2:] # Get elements from index 2 to the end (30, 40, 50)
print("arr[2:] ",slice2)

arr[1:4]  [20 30 40]
arr[:3]  [10 20 30]
arr[2:]  [30 40 50]
